# -*- coding: utf-8 -*-
"""Lab2_3_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kfm34YRiY5rZhZw4uHRfR48c6ND1z_Vd

**Лабораторна №2**

Завдання 2.3. Порівняння якості класифікаторів на прикладі класифікації сортів ірисів

КРОК 1. ЗАВАНТАЖЕННЯ ТА ВИВЧЕННЯ ДАНИХ
"""

# Імпортуємо набір даних Iris
from sklearn.datasets import load_iris
iris_dataset = load_iris()

# Виводимо ключі словника з даними
print('Ключі iris dataset: \n{}'.format(iris_dataset.keys()))

# Виводимо частину опису датасету
print(iris_dataset['DESCR'][:193] + "\n...")

# Виводимо назви класів (відповідей)
print('Назви відповідей: {}'.format(iris_dataset['target_names']))

# Виводимо назви ознак (характеристик)
print('Назви ознак: {}'.format(iris_dataset['feature_names']))

# Виводимо тип об'єкта з ознаками
print('Тип масиву data: {}'.format(type(iris_dataset['data'])))

# Виводимо розмірність масиву з ознаками
print('Форма масиву data: {}'.format(iris_dataset['data'].shape))

# Виводимо перші 5 прикладів з даними
print('Перші п’ять рядків масиву data:\n{}'.format(iris_dataset['data'][:5]))

# Виводимо тип об'єкта з мітками класів
print('Тип масиву target: {}'.format(type(iris_dataset['target'])))

# Виводимо всі мітки класів
print('Відповіді: {}'.format(iris_dataset['target']))

